import type { Car } from '@/types/car';

const PLACEHOLDER =
  'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=400';
const IMG2 = 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=400';
const IMG3 = 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400';
const IMG4 = 'https://images.unsplash.com/photo-1542362567-b07e54358753?w=400';
const IMG5 = 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=400';

export const CARS: Car[] = [
  {
    id: '1',
    name: 'Camry 2021',
    brand: 'Toyota',
    price: 28500,
    image: IMG2,
    images: [PLACEHOLDER, IMG2, IMG3, IMG4],
    availableColors: ['Pearl White', 'Midnight Black', 'Silver Sky', 'Supersonic Red'],
    year: 2021,
    mileage: '24,000 mi',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: '2',
    name: 'Civic 2022',
    brand: 'Honda',
    price: 26500,
    image: IMG3,
    images: [PLACEHOLDER, IMG2, IMG5],
    availableColors: ['Platinum White', 'Crystal Black', 'Lunar Silver'],
    year: 2022,
    mileage: '18,500 mi',
    fuelType: 'Gasoline',
    transmission: 'CVT',
  },
  {
    id: '3',
    name: 'Model 3 2023',
    brand: 'Tesla',
    price: 42990,
    image: IMG4,
    images: [PLACEHOLDER, IMG3, IMG4, IMG5],
    availableColors: ['Pure White', 'Solid Black', 'Midnight Silver', 'Deep Blue'],
    year: 2023,
    mileage: '5,200 mi',
    fuelType: 'Electric',
    transmission: 'Single-Speed',
  },
  {
    id: '4',
    name: 'F-150 2022',
    brand: 'Ford',
    price: 45200,
    image: IMG5,
    images: [PLACEHOLDER, IMG2],
    availableColors: ['Oxford White', 'Agate Black', 'Iconic Silver'],
    year: 2022,
    mileage: '22,000 mi',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: '5',
    name: '3 Series 2021',
    brand: 'BMW',
    price: 38900,
    image: IMG2,
    images: [PLACEHOLDER, IMG3, IMG5],
    availableColors: ['Alpine White', 'Black Sapphire', 'Mineral Grey'],
    year: 2021,
    mileage: '30,000 mi',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: '6',
    name: 'Accord 2023',
    brand: 'Honda',
    price: 30200,
    image: IMG2,
    images: [PLACEHOLDER, IMG2, IMG4],
    availableColors: ['Still Night Pearl', 'Platinum White', 'Lunar Silver'],
    year: 2023,
    mileage: '8,000 mi',
    fuelType: 'Hybrid',
    transmission: 'CVT',
  },
  {
    id: '7',
    name: 'RAV4 2022',
    brand: 'Toyota',
    price: 32100,
    image: IMG3,
    images: [PLACEHOLDER, IMG5, IMG3],
    availableColors: ['Magnetic Grey', 'Midnight Black', 'Blueprint'],
    year: 2022,
    mileage: '15,000 mi',
    fuelType: 'Hybrid',
    transmission: 'CVT',
  },
  {
    id: '8',
    name: 'Mustang 2022',
    brand: 'Ford',
    price: 38900,
    image: IMG4,
    images: [PLACEHOLDER, IMG2, IMG4, IMG5],
    availableColors: ['Race Red', 'Oxford White', 'Shadow Black', 'Grabber Blue'],
    year: 2022,
    mileage: '12,000 mi',
    fuelType: 'Gasoline',
    transmission: 'Manual',
  },
  {
    id: '9',
    name: 'C-Class 2021',
    brand: 'Mercedes-Benz',
    price: 42500,
    image: IMG5,
    images: [PLACEHOLDER, IMG3],
    availableColors: ['Polar White', 'Obsidian Black', 'Selenite Grey'],
    year: 2021,
    mileage: '28,000 mi',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: '10',
    name: 'Altima 2023',
    brand: 'Nissan',
    price: 28900,
    image: IMG3,
    images: [PLACEHOLDER, IMG2, IMG5],
    availableColors: ['Brilliant Silver', 'Gun Metallic', 'Scarlet Ember'],
    year: 2023,
    mileage: '6,500 mi',
    fuelType: 'Gasoline',
    transmission: 'CVT',
  },
  {
    id: '11',
    name: 'CX-5 2022',
    brand: 'Mazda',
    price: 29900,
    image: IMG4,
    images: [PLACEHOLDER, IMG4, IMG5],
    availableColors: ['Soul Red', 'Snowflake White', 'Jet Black'],
    year: 2022,
    mileage: '20,000 mi',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: '12',
    name: 'Corolla 2022',
    brand: 'Toyota',
    price: 22900,
    image: IMG5,
    images: [PLACEHOLDER, IMG2],
    availableColors: ['Super White', 'Midnight Black', 'Celestial Silver'],
    year: 2022,
    mileage: '14,000 mi',
    fuelType: 'Gasoline',
    transmission: 'CVT',
  },
  {
    id: '13',
    name: 'Pilot 2023',
    brand: 'Honda',
    price: 42100,
    image: IMG2,
    images: [PLACEHOLDER, IMG3, IMG4, IMG5],
    availableColors: ['Platinum White', 'Obsidian Blue', 'Modern Steel'],
    year: 2023,
    mileage: '4,000 mi',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: '14',
    name: 'Outback 2022',
    brand: 'Subaru',
    price: 31900,
    image: IMG3,
    images: [PLACEHOLDER, IMG5],
    availableColors: ['Crystal White', 'Magnetite Grey', 'Autumn Green'],
    year: 2022,
    mileage: '19,000 mi',
    fuelType: 'Gasoline',
    transmission: 'CVT',
  },
  {
    id: '15',
    name: 'Q5 2021',
    brand: 'Audi',
    price: 45800,
    image: IMG4,
    images: [PLACEHOLDER, IMG2, IMG3, IMG4],
    availableColors: ['Ibis White', 'Mythos Black', 'Daytona Grey'],
    year: 2021,
    mileage: '26,000 mi',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: '16',
    name: 'Explorer 2023',
    brand: 'Ford',
    price: 38900,
    image: IMG5,
    images: [PLACEHOLDER, IMG4],
    availableColors: ['Agate Black', 'Oxford White', 'Stone Grey'],
    year: 2023,
    mileage: '7,000 mi',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: '17',
    name: 'Highlander 2022',
    brand: 'Toyota',
    price: 41200,
    image: IMG2,
    images: [PLACEHOLDER, IMG2, IMG5],
    availableColors: ['Wind Chill Pearl', 'Midnight Black', 'Magnetic Grey'],
    year: 2022,
    mileage: '16,000 mi',
    fuelType: 'Hybrid',
    transmission: 'CVT',
  },
  {
    id: '18',
    name: 'Sentra 2023',
    brand: 'Nissan',
    price: 23900,
    image: IMG3,
    images: [PLACEHOLDER, IMG3],
    availableColors: ['Brilliant Silver', 'Gun Metallic', 'Scarlet Ember'],
    year: 2023,
    mileage: '3,500 mi',
    fuelType: 'Gasoline',
    transmission: 'CVT',
  },
  {
    id: '19',
    name: 'Tucson 2023',
    brand: 'Hyundai',
    price: 31200,
    image: IMG4,
    images: [PLACEHOLDER, IMG2, IMG4, IMG5],
    availableColors: ['Shimmering Silver', 'Hampton Grey', 'Amazon Grey'],
    year: 2023,
    mileage: '5,800 mi',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: '20',
    name: 'CR-V 2022',
    brand: 'Honda',
    price: 33500,
    image: IMG5,
    images: [PLACEHOLDER, IMG5],
    availableColors: ['Platinum White', 'Obsidian Blue', 'Lunar Silver'],
    year: 2022,
    mileage: '17,000 mi',
    fuelType: 'Gasoline',
    transmission: 'CVT',
  },
  {
    id: '21',
    name: 'Silverado 1500 2022',
    brand: 'Chevrolet',
    price: 42800,
    image: IMG2,
    images: [PLACEHOLDER, IMG2, IMG3],
    availableColors: ['Summit White', 'Black', 'Silver Ice'],
    year: 2022,
    mileage: '21,000 mi',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: '22',
    name: 'Escape 2023',
    brand: 'Ford',
    price: 29900,
    image: IMG3,
    images: [PLACEHOLDER, IMG4],
    availableColors: ['Oxford White', 'Agate Black', 'Carbonized Grey'],
    year: 2023,
    mileage: '9,000 mi',
    fuelType: 'Hybrid',
    transmission: 'CVT',
  },
  {
    id: '23',
    name: 'Optima 2021',
    brand: 'Kia',
    price: 26500,
    image: IMG4,
    images: [PLACEHOLDER, IMG2, IMG5],
    availableColors: ['Snow White Pearl', 'Ebony Black', 'Gravity Grey'],
    year: 2021,
    mileage: '32,000 mi',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: '24',
    name: 'Pathfinder 2023',
    brand: 'Nissan',
    price: 38200,
    image: IMG5,
    images: [PLACEHOLDER, IMG3, IMG4],
    availableColors: ['Pearl White', 'Gun Metallic', 'Boulder Grey'],
    year: 2023,
    mileage: '2,500 mi',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: '25',
    name: 'Enclave 2022',
    brand: 'Buick',
    price: 45200,
    image: IMG2,
    images: [PLACEHOLDER, IMG2, IMG5],
    availableColors: ['Summit White', 'Ebony Twilight', 'Red Quartz'],
    year: 2022,
    mileage: '11,000 mi',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: '26',
    name: 'RDX 2022',
    brand: 'Acura',
    price: 42900,
    image: IMG3,
    images: [PLACEHOLDER, IMG4, IMG5],
    availableColors: ['Platinum White', 'Apex Blue', 'Lunar Silver'],
    year: 2022,
    mileage: '13,000 mi',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
  },
  {
    id: '27',
    name: 'Malibu 2021',
    brand: 'Chevrolet',
    price: 24900,
    image: IMG4,
    images: [PLACEHOLDER, IMG2],
    availableColors: ['Summit White', 'Black', 'Silver Ice'],
    year: 2021,
    mileage: '35,000 mi',
    fuelType: 'Gasoline',
    transmission: 'CVT',
  },
];
